config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}
  resources :contacts
  resources :users do
    resource :profile
  end
  get '/about' => 'pages#about'
  root 'pages#home' # home page routes to pages controller, and home action

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true  
  validates :email, presence: true  
end

app/models/plan.rb
class Plan < ActiveRecord::Base
   has_many :users 
    
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
    
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
    
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  def save_with_payment
    if valid?
     #customer = Stripe::Customer.create(description: email, plan: plan_id, source: stripe_card_token) 
     customer = Stripe::Customer.create(description: email, plan: plan_id, source: "tok_17E01wFdrePgxD3LOBdkYar3") 
     self.stripe_cutstomer_token = customer.id
     save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :test, :stripe_card_token, :email, :password, :password_confirmation)} 
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
        @contact = Contact.new
    end
    
    def create
        @contact = Contact.new(contact_params)
        
        if @contact.save
          name = params[:contact][:name]
          email = params[:contact][:email]
          body = params[:contact][:comments]
          
          ContactMailer.contact_email(name,email,body).deliver
          
          flash[:success] = "Message sent." 
          redirect_to new_contact_path
        else
          flash[:danger] = "Error occured, message not sent." 
          redirect_to new_contact_path
        end
    end
    
    private
        def contact_params
            params.require(:contact).permit(:name, :email, :comments)    
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @basic_plan = Plan.find(1)
        @pro_plan = Plan.find(2)
    end
    
    def about
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  
    def new
      # form for user to fill out own profile
      @user = User.find(params[:user_id])
      @profile = Profile.new
    end
    
    def create
     @user = User.find(params[:user_id]) 
     @profile = @user.build_profile(profile_params)
     if @profile.save
       flash[:success] = "Profile Updated!"
       redirect_to user_path(params[:user_id]) 
     else
       render action: :new 
     end
    end
    
    def edit
     @user = User.find(params[:user_id]) 
     @profile = @user.profile
    end
     
    def update
      @user = User.find(params[:user_id]) 
      @profile = @user.profile
      if @profile.update_attributes(profile_params)
        flash[:success] = "Profile Updated!"
        redirect_to user_path(params[:user_id]) 
      else
        render action: :edit
      end
    end
    
    private
    
      def profile_params
        params.require(:profile).permit(:first_name, :last_name, :avatar, :job_title, :phone_number, :contact_email, :description)
      end
      
      def only_current_user
       @user = User.find(params[:user_id]) # get user from url parameters
       redirect_to(root_url) unless @user == current_user # check if it matches logged in user
      end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :select_plan, only: :new
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
            resource.save_with_payment
        else
            resource.save
        end
      end
    end
  end
  
  private
  
  def select_plan
    unless params[:plan] && (params[:plan]  == '1' || params[:plan]  == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
    def index
      @users = User.all  
    end
  
    def show
      @user = User.find(params[:id])          
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def job_title_icon
        if @user.profile.job_title == "Developer"
            "<i class='fa fa-code'></i>".html_safe
        elsif @user.profile.job_title == "Entrepreneur"
            "<i class='fa fa-lightbulb-o'></i>".html_safe
        elsif @user.profile.job_title == "Investor"
            "<i class='fa fa-dollar'></i>".html_safe
        end
    end
end

app/views/contacts/new.html.erb
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h1 class="text-center">Contact Us</h1>
        <p class="text-center">Reach out if you have any questions or comments</p>
        <div class="well">
            <%= form_for @contact do |f| %>
                <div class="form-group">
                    <%= f.label :name %>
                    <%= f.text_field :name, class:'form-control' %>
                </div>
               
                <div class="form-group">
                    <%= f.label :email %>
                    <%= f.email_field :email, class:'form-control' %>
                </div>
               
                <div class="form-group">
                    <%= f.label :comments %>
                    <%= f.text_area :comments, class:'form-control' %>
                </div>
                
                <%= f.submit 'Submit', class: 'btn btn-default' %>
               
           <% end %>
       </div> 
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DevMatch</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript '%>
  <%= javascript_include_tag 'application'%>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-users"></i>
          Dev Match
        <% end %>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%= link_to 'About', about_path, class: 'navbar-brand' %>
          <%= link_to 'Contact Us', new_contact_path, class: 'navbar-brand' %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Action</a></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        
        <div class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
          <% else %>
            <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>
          <% end %>
        </div>
        
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to 'Community', users_path, class: 'navbar-brand' %></li>
            <li><%= link_to 'My Account', edit_user_registration_path, class: 'navbar-brand' %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  
<div class="container">
  <% flash.each do |k,v| %>
    <%= content_tag :div, v, class: "alert alert-#{k}" %> 
  <% end %>
  
    <%= yield %>
</div>

</body>
</html>

app/views/pages/about.html.erb
<h2>About Us</h2>
<p>Welcome to DevMatch. We are a community of developers, entreupreneurs,
and investors interested in meeting one another and sharing ideas.</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
    <h1>Welcome to Dev Match</h1>
    <h3>Membership site for entreupreneurs and developers.</h3>
</div>

<div class="row">
  <% if user_signed_in? %> <!--the user is signed in -->
  
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Your Profile</h2>
        <% if current_user.profile %>
          <%= link_to "Edit your profile!", edit_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block'%>
          <%= link_to "View your profile!", user_path(current_user), class: 'btn btn-default btn-lg btn-block'%>
        <% else %>
          <p>Create your profile so that you can share your information with the community.</p>
          <%= link_to "Create your profile!", new_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block'%>
        <% end %>
      </div>
    </div>
    
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">The Community</h2>
        <p>Visit the community to meet other developers, entreupreneurs, and investors!</p>
        <%= link_to "Visit the community", users_path, class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
    
  <% else %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Basic Membership</h2>
        <h4>Sign up for free and get basic access to the community.</h4>
        </br>
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Pro Membership</h2>
        <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
        <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, html: {multipart: true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Developer', 'Entrepreneur', 'Investor'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'form-control' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Edit Your Profile</h1>
        <p class="text-center">Be a part of the Dev Match community</p>
        <div class="well">
          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Create Your Profile</h1>
        <p class="text-center">Be a part of the Dev Match community</p>
        <div class="well">
          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-8-md-offset-2">
    <h1 class="text-center">DevMatch Community</h1>
    <p class="text-center">Welcome to the DevMatch Community. Users must fill out a profile to be visible to the community.</p>
    <ul class="list-unstyled">
      <% @users.each do |user| %>
          <% if user.profile %>
            <li>
              
              <div class="well row <%= cycle('white-bg', '') %>">
                <div class="col-sm-8 text-center">
                  <% if user.profile.avatar %>
                    <%= link_to user do %>
                      <%= image_tag user.profile.avatar.url(:thumb), class: "user-index-avatar" %>
                    <% end %>
                  <% end %>
                </div>
                
                <div>
                  <%= link_to user do %>
                    <h2><%= user.profile.first_name %> <%= user.profile.last_name %><br></h2>
                  <% end %>
                  <p>
                    <%= user.profile.job_title %>
                    <% if user.plan_id == 2 %>
                      <span class="label label-danger">PRO</span>
                    <% end %>
                  </p>
                  <%= user.id%><br>
                </div>
              </div>
            </li>
          <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3 text-center">
    <%= image_tag @user.profile.avatar.url, class: 'user-show-avatar' %><br/>
  </div>
  <div class="col-md-6">
    <h1><%= @user.profile.first_name %> <%= @user.profile.last_name %></h1>
    <h3><span class="job-title-icon"><%= job_title_icon %></span> <%= @user.profile.job_title%></h3>
    <div class="well profile-block profile-description">
      <h3>Description</h3>
      <%= @user.profile.description%>
    </div>
    <% if current_user.plan_id == 2 %>
    <div class="well profile-block contact-info">
      <h3>Contact Info</h3>
        <%= @user.profile.contact_email%><br/>
        <%= @user.profile.phone_number%><br/>
    </div>
    <% end %>
  </div>
</div>